name: CatSeedLogin
main: cc.baka9.catseedlogin.CatSeedLogin
author: CatSeed
version: ${version}
api-version: 1.13
commands:
  login:
    description: 使用密码登录
    usage: /<command> 密码
    aliases: [l]
  register:
    description: 注册密码
    usage: /<command> 密码 重复密码
    aliases: [reg]
  bindemail:
    description: 绑定邮箱,重置密码
    usage:
      |
      /<command> set 邮箱
      /<command> verify 验证码
    aliases: [bdmail]
  resetpassword:
    description: 忘记密码,重置密码
    usage:
      |
      /<command> forget
      /<command> re 验证码 新密码
    aliases: [repw]
  changepassword:
    description: 修改密码
    usage: /<command> 旧密码 新密码 重复新密码
    aliases: [changepw]
  adminsetpassword:
    description: 管理员强制设置玩家密码
    usage: /<command> 玩家名 密码
    aliases: [adminsetpw]
    permission: catseedlogin.command.adminsetpassword
  catseedlogin:
    description: 其他指令
    usage: /<command> reload 重载配置文件
    aliases: [cslogin]
    permission: catseedlogin.command.catseedlogin
  unregister:
    description: 销户
    usage: /<command> 当前密码 重复密码
    aliases: [unreg]