maxLogPerIP: 1
spawnWorld: "world"
specialSymbolsIDLimit: true
IDMinLength: 3
IDMaxLength: 16
noDamageBeforeLogin: true
loginTimeout: 60
backAfterLogin: true
languageFile: "lang_zhCN.yml"
debug: false
forceStrongPasswd: true